version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
